apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: gateway-service
          image: jdavidaraujo/vehicle-position-solution_gateway-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: POI_SERVICE_URL
              value: http://poi-service:8082
            - name: VEHICLE_SERVICE_URL
              value: http://vehicle-service:8081
            - name: VEHICLE_POSTION_SEARCH_SERVICE_URL
              value: http://vehicle-position-search-service:8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: LoadBalancer