apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-position-search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-position-search-service
  template:
    metadata:
      labels:
        app: vehicle-position-search-service
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
        - name: vehicle-position-search-service
          image: jdavidaraujo/vehicle-position-solution_vehicle-position-search-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/tb_veiculo"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_REDIS_HOST
              value: "redis"
            - name: SPRING_REDIS_PORT
              value: "6379"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-position-search-service
  labels:
    app: vehicle-position-search-service
spec:
  selector:
    app: vehicle-position-search-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vehicle-position-search-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vehicle-position-search-service
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
