spring:
  application:
    name: vehicle-position-search-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: redis
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      time-to-live: 60000
      cache-null-values: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 10000
      pool-name: vehiclePositionSearchServicePoolConnection
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    kubernetes:
      discovery:
        all-namespaces: true
server:
  port: 8080
  cloud:
    openfeign:
      client:
        config:
          poi-service:
            connect-timeout: 5000
            read-timeout: 5000
            url: http://localhost:8082
          vehicle-service:
            #connect-timeout: 5000
            read-timeout: 5000
            url: http://localhost:8081